- apache2_module:
    state: present
    name: rewrite

- name: enabled mod_rewrite
  apache2_module: 
    name=alias
    state=present
    
- name: enabled mod_rewrite
  apache2_module: 
    name=proxy
    state=present
    
- name: enabled mod_rewrite
  apache2_module: 
    name=proxy_fcgi
    state=present
