- name: Unarchive a file that needs to be downloaded (added in 2.0)
  unarchive:
    src: "{{ url_phpmyadmin }}"
    dest: /var/www/html
    remote_src: yes

- name: Move foo to bar
  command: mv /var/www/html/"{{ directory_phpmyadmin_to_rename }}"  /var/www/html/phpmyadmin

- name: Move foo to bar
  command: mv /var/www/html/phpmyadmin/config.sample.inc.php  /var/www/html/phpmyadmin/config.inc.php

- name: Change path into pckage.json for script
  lineinfile:
    path: /var/www/html/phpmyadmin/config.inc.php
    regexp: '^(.*)blowfish_secret(.*)$'
    line: "$cfg['blowfish_secret'] = '6PsUICt;G:KBeyW-5waDBv}IGxrq}[mX';"
    backrefs: yes
  become: yes
  become_user: www-data

- name: Change path into pckage.json for script
  lineinfile:
    path: /var/www/html/phpmyadmin/config.inc.php
    regexp: '^(.*)controluser(.*)$'
    line: "$cfg['Servers'][$i]['controluser'] = 'pma';"
    backrefs: yes
  become: yes
  become_user: www-data

- name: Change path into pckage.json for script
  lineinfile:
    path: /var/www/html/phpmyadmin/config.inc.php
    regexp: '^(.*)controlpass(.*)$'
    line: "$cfg['Servers'][$i]['controlpass'] = '4321';"
    backrefs: yes
  become: yes
  become_user: www-data

- name: Change path into pckage.json for script
  lineinfile:
    path: /var/www/html/phpmyadmin/config.inc.php
    regexp: '^(.*)pmadb(.*)$'
    line: "$cfg['Servers'][$i]['pmadb'] = 'phpmyadmin';"
    backrefs: yes
  become: yes
  become_user: www-data

- name: Change path into pckage.json for script
  lineinfile:
    path: /var/www/html/phpmyadmin/config.inc.php
    regexp: '^(.*)bookmarktable(.*)$'
    line: "$cfg['Servers'][$i]['bookmarktable'] = 'pma__bookmark';"
    backrefs: yes
  become: yes
  become_user: www-data

- name: Change path into pckage.json for script
  lineinfile:
    path: /var/www/html/phpmyadmin/config.inc.php
    regexp: '^(.*)relation(.*)$'
    line: "$cfg['Servers'][$i]['relation'] = 'pma__relation';"
    backrefs: yes
  become: yes
  become_user: www-data

- name: Change path into pckage.json for script
  lineinfile:
    path: /var/www/html/phpmyadmin/config.inc.php
    regexp: '^(.*)table_info(.*)$'
    line: "$cfg['Servers'][$i]['table_info'] = 'pma__table_info';"
    backrefs: yes
  become: yes
  become_user: www-data

- name: Change path into pckage.json for script
  lineinfile:
    path: /var/www/html/phpmyadmin/config.inc.php
    regexp: '^(.*)table_coords(.*)$'
    line: "$cfg['Servers'][$i]['table_coords'] = 'pma__table_coords';"
    backrefs: yes
  become: yes
  become_user: www-data

- name: Change path into pckage.json for script
  lineinfile:
    path: /var/www/html/phpmyadmin/config.inc.php
    regexp: '^(.*)pdf_pages(.*)$'
    line: "$cfg['Servers'][$i]['pdf_pages'] = 'pma__pdf_pages';"
    backrefs: yes
  become: yes
  become_user: www-data

- name: Change path into pckage.json for script
  lineinfile:
    path: /var/www/html/phpmyadmin/config.inc.php
    regexp: '^(.*)column_info(.*)$'
    line: "$cfg['Servers'][$i]['column_info'] = 'pma__column_info';"
    backrefs: yes
  become: yes
  become_user: www-data

- name: Change path into pckage.json for script
  lineinfile:
    path: /var/www/html/phpmyadmin/config.inc.php
    regexp: "^(.*)\\['history'\\](.*)$"
    line: "$cfg['Servers'][$i]['history'] = 'pma__history';"
    backrefs: yes
  become: yes
  become_user: www-data

- name: Change path into pckage.json for script
  lineinfile:
    path: /var/www/html/phpmyadmin/config.inc.php
    regexp: '^(.*)table_uiprefs(.*)$'
    line: "$cfg['Servers'][$i]['table_uiprefs'] = 'pma__table_uiprefs';"
    backrefs: yes
  become: yes
  become_user: www-data

- name: Change path into pckage.json for script
  lineinfile:
    path: /var/www/html/phpmyadmin/config.inc.php
    regexp: '^(.*)tracking(.*)$'
    line: "$cfg['Servers'][$i]['tracking'] = 'pma__tracking';"
    backrefs: yes
  become: yes
  become_user: www-data

- name: Change path into pckage.json for script
  lineinfile:
    path: /var/www/html/phpmyadmin/config.inc.php
    regexp: '^(.*)userconfig(.*)$'
    line: "$cfg['Servers'][$i]['userconfig'] = 'pma__userconfig';"
    backrefs: yes
  become: yes
  become_user: www-data

- name: Change path into pckage.json for script
  lineinfile:
    path: /var/www/html/phpmyadmin/config.inc.php
    regexp: '^(.*)recent(.*)$'
    line: "$cfg['Servers'][$i]['recent'] = 'pma__recent';"
    backrefs: yes
  become: yes
  become_user: www-data

- name: Change path into pckage.json for script
  lineinfile:
    path: /var/www/html/phpmyadmin/config.inc.php
    regexp: '^(.*)favorite(.*)$'
    line: "$cfg['Servers'][$i]['favorite'] = 'pma__favorite';"
    backrefs: yes
  become: yes
  become_user: www-data

- name: Change path into pckage.json for script
  lineinfile:
    path: /var/www/html/phpmyadmin/config.inc.php
    regexp: "^(.*)\\['users'\\](.*)$"
    line: "$cfg['Servers'][$i]['users'] = 'pma__users';"
    backrefs: yes
  become: yes
  become_user: www-data

- name: Change path into pckage.json for script
  lineinfile:
    path: /var/www/html/phpmyadmin/config.inc.php
    regexp: '^(.*)usergroups(.*)$'
    line: "$cfg['Servers'][$i]['usergroups'] = 'pma__usergroups';"
    backrefs: yes
  become: yes
  become_user: www-data

- name: Change path into pckage.json for script
  lineinfile:
    path: /var/www/html/phpmyadmin/config.inc.php
    regexp: '^(.*)navigationhiding(.*)$'
    line: "$cfg['Servers'][$i]['navigationhiding'] = 'pma__navigationhiding';"
    backrefs: yes
  become: yes
  become_user: www-data

- name: Change path into pckage.json for script
  lineinfile:
    path: /var/www/html/phpmyadmin/config.inc.php
    regexp: '^(.*)savedsearches(.*)$'
    line: "$cfg['Servers'][$i]['savedsearches'] = 'pma__savedsearches';"
    backrefs: yes
  become: yes
  become_user: www-data


- name: Change path into pckage.json for script
  lineinfile:
    path: /var/www/html/phpmyadmin/config.inc.php
    regexp: '^(.*)central_columns(.*)$'
    line: "$cfg['Servers'][$i]['central_columns'] = 'pma__central_columns';"
    backrefs: yes
  become: yes
  become_user: www-data

- name: Change path into pckage.json for script
  lineinfile:
    path: /var/www/html/phpmyadmin/config.inc.php
    regexp: '^(.*)designer_settings(.*)$'
    line: "$cfg['Servers'][$i]['designer_settings'] = 'pma__designer_settings';"
    backrefs: yes
  become: yes
  become_user: www-data

- name: Change path into pckage.json for script
  lineinfile:
    path: /var/www/html/phpmyadmin/config.inc.php
    regexp: '^(.*)export_templates(.*)$'
    line: "$cfg['Servers'][$i]['export_templates'] = 'pma__export_templates';"
    backrefs: yes
  become: yes
  become_user: www-data

- name: Create a new database with name 'bobdata'
  mysql_db:
    name: phpmyadmin
    state: present
    login_user: root
    login_password: "{{ password_root_mysql }}"
    encoding: "utf8"

- name: Restore database
  mysql_db:
    login_user: root
    login_password: "{{ password_root_mysql }}"
    state: import
    name: phpmyadmin
    target: /var/www/html/phpmyadmin/sql/create_tables.sql

- name: Create database user for project
  mysql_user:
    login_user: root
    login_password: "{{ password_root_mysql }}"
    host: "localhost"
    name: 'pma'
    password: '4321'
    priv: 'phpmyadmin.*:ALL'
    state: present

- name: mkdir adminer
  file:
    path: "/var/www/html/phpmyadmin/tmp"
    state: directory
    mode: 0755
    recurse: yes
  become: yes
  become_user: www-data

- name: line insert
  lineinfile:
    path: /var/www/html/phpmyadmin/config.inc.php
    line: "$cfg['TempDir'] = '/var/www/html/phpmyadmin/tmp';"
    insertafter: EOF
  become: yes
  become_user: www-data

- name: Remove directory
    file:
      path: /var/www/html/phpmyadmin/setup
      state: absent



