- name: Unarchive a file that needs to be downloaded (added in 2.0)
  unarchive:
    src: "{{ url_phpmyadmin }}"
    dest: /var/www/html
    remote_src: yes

- name: Move foo to bar
  command: mv /var/www/html/"{{ directory_phpmyadmin_to_rename }}"  /var/www/html/phpmyadmin

- name: Move foo to bar
  command: mv /var/www/html/phpmyadmin/config.sample.inc.php  /var/www/html/phpmyadmin/config.sample.inc.php

- name: Change path into pckage.json for script
  lineinfile:
    path: /var/www/html/package.json
    regexp: '^(.*)blowfish_secret(.*)$'
    line: "$cfg['blowfish_secret'] = '6PsUICt;G:KBeyW-5waDBv}IGxrq}[mX';"
    backrefs: yes
  when: "{{ installSassLoader }} == true"
  become: yes
  become_user: vagrant

